export * from "./course.schema";
export * from "./coupon.schema";
export * from "./roadmap.schema";
export * from "./click.schema";
export * from "./platform.schema";
export * from "./category.schema";
export * from "./settings.schema";
export * from "./auth.schema";
export * from "./shared";
